=== jayansh/R3Transform/com.release3.transform.rule/rules.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.release3.com/rules"
	xmlns:tns="http://www.release3.com/rules" elementFormDefault="qualified">
	<element name="Rules">

		<complexType >
		
			
			<sequence>
				<element name="DatabaseBlockRule" maxOccurs="8" minOccurs="1" >
					<complexType>
						<sequence>
							<element name="IsDBBlockType" type="boolean"></element>

							<element name="QueryDataSourceType">

								<simpleType>
									<restriction base="string">
										<enumeration value="Table" />
										<enumeration value="Other" />
									</restriction>
								</simpleType>

							</element>

							<element name="HasQueryDataSourceName" type="boolean"></element>

							<element name="Result">
								<simpleType>
									<restriction base="string">
										<enumeration value="DBBlock" />
										<enumeration value="NonDBBlock" />
									</restriction>
								</simpleType>

							</element>

						</sequence>
						<attribute name="name" use="required"/>
					</complexType>
				</element>
			</sequence>
		</complexType>

	</element>





</schema>

=== jayansh/R3Transform/com.release3.transform.rule/Rules.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Rules xmlns:tns="http://www.release3.com/rules"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.release3.com/rules rules.xsd ">
	<tns:DatabaseBlockRule name="Rule1">
		<tns:IsDBBlockType>true</tns:IsDBBlockType>
		<tns:QueryDataSourceType>Table</tns:QueryDataSourceType>
		<tns:HasQueryDataSourceName>true</tns:HasQueryDataSourceName>
		<tns:Result>DBBlock</tns:Result>
	</tns:DatabaseBlockRule>
	<tns:DatabaseBlockRule name="Rule2">
		<tns:IsDBBlockType>true</tns:IsDBBlockType>
		<tns:QueryDataSourceType>Other</tns:QueryDataSourceType>
		<tns:HasQueryDataSourceName>true</tns:HasQueryDataSourceName>
		<tns:Result>DBBlock</tns:Result>
	</tns:DatabaseBlockRule>
	<tns:DatabaseBlockRule name="Rule3">
		<tns:IsDBBlockType>true</tns:IsDBBlockType>
		<tns:QueryDataSourceType>Table</tns:QueryDataSourceType>
		<tns:HasQueryDataSourceName>false</tns:HasQueryDataSourceName>
		<tns:Result>DBBlock</tns:Result>
	</tns:DatabaseBlockRule>
	<tns:DatabaseBlockRule name="Rule4">
		<tns:IsDBBlockType>true</tns:IsDBBlockType>
		<tns:QueryDataSourceType>Other</tns:QueryDataSourceType>
		<tns:HasQueryDataSourceName>false</tns:HasQueryDataSourceName>
		<tns:Result>NonDBBlock</tns:Result>
	</tns:DatabaseBlockRule>
	<tns:DatabaseBlockRule name="Rule5">
		<tns:IsDBBlockType>false</tns:IsDBBlockType>
		<tns:QueryDataSourceType>Table</tns:QueryDataSourceType>
		<tns:HasQueryDataSourceName>true</tns:HasQueryDataSourceName>
		<tns:Result>NonDBBlock</tns:Result>
	</tns:DatabaseBlockRule>
	<tns:DatabaseBlockRule name="Rule6">
		<tns:IsDBBlockType>false</tns:IsDBBlockType>
		<tns:QueryDataSourceType>Other</tns:QueryDataSourceType>
		<tns:HasQueryDataSourceName>true</tns:HasQueryDataSourceName>
		<tns:Result>NonDBBlock</tns:Result>
	</tns:DatabaseBlockRule>
	<tns:DatabaseBlockRule name="Rule7">
		<tns:IsDBBlockType>false</tns:IsDBBlockType>
		<tns:QueryDataSourceType>Table</tns:QueryDataSourceType>
		<tns:HasQueryDataSourceName>false</tns:HasQueryDataSourceName>
		<tns:Result>NonDBBlock</tns:Result>
	</tns:DatabaseBlockRule>
	<tns:DatabaseBlockRule name="Rule8">
		<tns:IsDBBlockType>false</tns:IsDBBlockType>
		<tns:QueryDataSourceType>Other</tns:QueryDataSourceType>
		<tns:HasQueryDataSourceName>false</tns:HasQueryDataSourceName>
		<tns:Result>NonDBBlock</tns:Result>
	</tns:DatabaseBlockRule>
</tns:Rules>
