=== jayansh/R3Transform/com.release3.tf.jaxb/builtins/R3builtinlist.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.release3.com/R3Builtin/builtinlist"
	 elementFormDefault="qualified" xmlns:Q1="http://www.release3.com/R3Builtin/builtinlist">

    
			<element name="R3Builtlist" >
				<complexType>
					<sequence>
						
						<element name="BuiltinAction"
							type="Q1:BuiltinsMap" maxOccurs="unbounded" minOccurs="0">
						</element>
					</sequence>
					<attribute name="Name" type="string"></attribute>
				</complexType>
			</element>
		
    <complexType name="BuiltinsMap">
    	<sequence>

    		<element name="JavaEquivalentBuiltin" type="string"
    			maxOccurs="1" minOccurs="0">
    		</element>
    		<element name="CrudEquivalentBuiltin" type="string" maxOccurs="1" minOccurs="0"></element>
    	</sequence>
    	<attribute name="FormBuiltin" type="string"></attribute>
    </complexType>
</schema>

=== jayansh/R3Transform/com.release3.tf.jaxb/builtins/Builtinlist.xml
<?xml version="1.0" encoding="UTF-8"?>
<R3Builtlist Name="" xmlns="http://www.release3.com/R3Builtin/builtinlist"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.release3.com/R3Builtin/builtinlist R3builtinlist.xsd ">
	<BuiltinAction FormBuiltin="ABORT_QUERY">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ADD_GROUP_COLUMN">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ADD_GROUP_ROW">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ADD_LIST_ELEMENT">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ADD_PARAMETER">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CALL_FORM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CALL_INPUT">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CANCEL_REPORT_OBJECT">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CHECK_RECORD_UNIQUENESS">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CHECKBOX_CHECKED">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CLEAR_BLOCK">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CLEAR_EOL">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CLEAR_FORM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CLEAR_ITEM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CLEAR_LIST">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CLEAR_MESSAGE">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CLEAR_RECORD">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CLOSE_FORM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="COMMIT_FORM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CONVERT_OTHER_VALUE">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="COPY">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="COPY_REGION">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="COPY_REPORT_OUTPUT">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="COUNT_QUERY">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CREATE_GROUP">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CREATE_GROUP_FROM_QUERY">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CREATE_PARAMETER_LIST">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CREATE_QUERIED_RECORD">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CREATE_RECORD">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CREATE_TIMER">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CREATE_VAR">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="CUT_REGION">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DBMS_ERROR_CODE">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DBMS_ERROR_TEXT">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DEFAULT_VALUE">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DELETE_GROUP">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DELETE_GROUP_ROW">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DELETE_LIST_ELEMENT">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DELETE_PARAMETER">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DELETE_RECORD">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DELETE_TIMER">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DESTROY_PARAMETER_LIST">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DISPLAY_ERROR">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DISPLAY_ITEM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DOWN">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DO_KEY">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DUMMY_REFERENCE">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DUPLICATE_ITEM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="DUPLICATE_RECORD">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="EDIT_TEXTITEM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ENFORCE_COLUMN_SECURITY">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ENTER">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ENTER_QUERY">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ERASE">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ERROR_CODE">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ERROR_TEXT">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="ERROR_TYPE">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="EXECUTE_QUERY">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="EXECUTE_TRIGGER">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="EXIT_FORM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FETCH_RECORDS">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_ALERT">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_BLOCK">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_CANVAS">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_COLUMN">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_EDITOR">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_FORM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_GROUP">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_ITEM">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_LOV">
		<!--<JavaEquivalentBuiltin>"comment out"</JavaEquivalentBuiltin>-->
	</BuiltinAction>

	<BuiltinAction FormBuiltin="FIND_MENU_ITEM">
