=== jayansh/R3Transform/com.release3.tf.jaxb/builtins/R3BuiltinsPropertyMap.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.release3.com/Builtins/PropertyMap"
	xmlns:tns="http://www.release3.com/Builtins/PropertyMap"
	elementFormDefault="qualified">

	<element name="R3BuiltinsMap">
		<complexType>
			<sequence>
				<element name="PropertyMap" maxOccurs="unbounded" minOccurs="0"
					type="tns:PropertyMapType">
				</element>
			</sequence>
		</complexType>
	</element>





	<complexType name="PropertyMapType">
		<sequence>
			<element name="FormProperty" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="JavaProperty" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="JavaDataType" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="Negation" type="boolean" maxOccurs="1"
				minOccurs="0">
			</element>
		</sequence>
	</complexType>
</schema>

=== jayansh/R3Transform/com.release3.tf.jaxb/builtins/R3BuiltinsPropertyMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
    Copyright (c) 2009, 2013 ObanSoft Inc. and others.
    All rights reserved. This program and the accompanying materials
    are made available under the terms of the Eclipse Public License v1.0
    which accompanies this distribution, and is available at
    http://www.eclipse.org/legal/epl-v10.html
   
    Contributors:
        Jayansh Shinde
 -->

<R3BuiltinsMap xmlns:tns="http://www.release3.com/Builtins/PropertyMap" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.release3.com/Builtins/PropertyMap R3BuiltinsPropertyMap.xsd ">
	<PropertyMap>
		<FormProperty>ALIGNMENT</FormProperty>
		<JavaProperty>Align</JavaProperty>
		<JavaDataType>String</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>BACKGROUND_COLOR</FormProperty>
		<JavaProperty>BackgroundColor</JavaProperty>
		<JavaDataType>String</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>DISPLAYED</FormProperty>
		<JavaProperty>Rendered</JavaProperty>
		<JavaDataType>Boolean</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>ENABLED</FormProperty>
		<JavaProperty>Disabled</JavaProperty>
		<JavaDataType>Boolean</JavaDataType>
		<Negation>true</Negation>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>REQUIRED</FormProperty>
		<JavaProperty>required</JavaProperty>
		<JavaDataType>Boolean</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>VISIBLE</FormProperty>
		<JavaProperty>render</JavaProperty>
		<JavaDataType>boolean</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>PROMPT_TEXT</FormProperty>
		<JavaProperty>Label</JavaProperty>
		<JavaDataType>String</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>LABEL</FormProperty>
		<JavaProperty>Label</JavaProperty>
		<JavaDataType>String</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>HEIGHT</FormProperty>
		<JavaProperty>height</JavaProperty>
		<JavaDataType>Integer</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>WIDTH</FormProperty>
		<JavaProperty>size</JavaProperty>
		<JavaDataType>Integer</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>HINT_TEXT</FormProperty>
		<JavaProperty>tooltip</JavaProperty>
		<JavaDataType>String</JavaDataType>
	</PropertyMap>
	<PropertyMap>
		<FormProperty>FOREGROUND_COLOR</FormProperty>
		<JavaProperty>ForegroundColor</JavaProperty>
		<JavaDataType>String</JavaDataType>
	</PropertyMap>
</R3BuiltinsMap>
